definitions:
  inputs.PostInput:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  post.Post:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "2.0"
paths:
  /posts:
    get:
      consumes:
      - '*/*'
      description: description over here
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: /post
      tags:
      - Post
    post:
      consumes:
      - '*/*'
      description: description over here
      parameters:
      - description: Add Post
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/inputs.PostInput'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: /post
      tags:
      - Post
  /posts/{id}:
    delete:
      consumes:
      - '*/*'
      description: description over here
      parameters:
      - description: Post Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: /post/:id
      tags:
      - Post
    get:
      consumes:
      - '*/*'
      description: description over here
      parameters:
      - description: Post Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/post.Post'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: /post/:id
      tags:
      - Post
    put:
      consumes:
      - '*/*'
      description: description over here
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Post
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/inputs.PostInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: /post/:id
      tags:
      - Post
schemes:
- http
swagger: "2.0"
